name: Build Test and Deploy

run-name: Deploy to vps

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      # Setup Node.js
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "22.8.x"

      # checkout repo
      - name: Checkout main
        uses: actions/checkout@v3

      # install node dependencies
      - name: Install dependencies
        run: npm install

      # Tests
      - name: Run tests
        run: npm run test

      # Build for production without __tests__ directory
      - name: Build
        run: npm run build


      # Deployment

      - name: Deploy
        env:
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_USER: ${{ secrets.VPS_USER }}
          VPS_PRIV_KEY: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          VPS_PATH: ${{ secrets.VPS_PATH }}
          VPS_PORT: ${{ secrets.VPS_PORT }}
        run: |
          # Create dist.tar.gz archive
          chmod +x tar.sh
          ./tar.sh
          
          # Create file with private key to use for ssh connection
          echo -e "$VPS_PRIV_KEY" | tr -d '\r' > private_key
          chmod 600 private_key
          
          # copy the archive to the vps
          scp -P $VPS_PORT -i private_key -o StrictHostKeyChecking=no dist.tar.gz $VPS_USER@$VPS_HOST:$VPS_PATH
          
          # execute deploy script on vps
          ssh -t -p $VPS_PORT -i private_key -o StrictHostKeyChecking=no $VPS_USER@$VPS_HOST "cd $VPS_PATH && ./deploy.sh"